type HandoffShot = {
  clipId?: string;
  clipName?: string;
  sourceUrl?: string | null;
  relinkStatus?: 'ready' | 'missing-source' | string;
  trackName?: string;
  source?: {
    handleInFrame?: number;
    handleOutFrame?: number;
  };
};

type HandoffWarningManifest = {
  schema?: string;
  project?: {
    name?: string;
    fps?: number;
    width?: number;
    height?: number;
    timelineDurationFrames?: number;
  };
  color?: {
    openColorIO?: {
      configPath?: string;
      recommendedConfig?: string;
      inputColorSpace?: string;
      outputColorSpace?: string;
      display?: string;
      view?: string;
    };
  };
  shots?: HandoffShot[];
  warnings?: string[];
};

export type VfxApplicationScript = {
  extension: 'nk' | 'py';
  contents: string;
};

const parseManifest = (manifest: string | HandoffWarningManifest): HandoffWarningManifest => {
  const parsed = typeof manifest === 'string' ? JSON.parse(manifest) : manifest;
  if (!parsed || typeof parsed !== 'object') {
    throw new Error('VFX script export needs a VFX handoff manifest object.');
  }
  if (parsed.schema !== 'ai-video-production-editor.vfx-handoff.v1') {
    throw new Error('VFX script export needs an ai-video-production-editor.vfx-handoff.v1 manifest.');
  }
  return parsed;
};

const scriptString = (value: unknown) => String(value || '');

const escapeNuke = (value: unknown) =>
  scriptString(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');

const escapePython = (value: unknown) =>
  scriptString(value)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n');

const sanitizeNodeName = (value: unknown, fallback = 'shot') => {
  const cleaned = scriptString(value)
    .replace(/[^a-zA-Z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return cleaned || fallback;
};

const toNumber = (value: unknown, fallback: number) => {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : fallback;
};

const getReadyShots = (manifest: HandoffWarningManifest) =>
  (manifest.shots || []).filter((shot) => shot.relinkStatus === 'ready' && shot.sourceUrl);

const getWarnings = (manifest: HandoffWarningManifest) => {
  const warnings = [...(manifest.warnings || [])];
  (manifest.shots || []).forEach((shot) => {
    if (shot.relinkStatus !== 'ready') {
      warnings.push(`Shot "${shot.clipId || shot.clipName || 'unknown'}" has no relinkable source and was not converted into a Read node.`);
    }
  });
  return warnings;
};

export const buildNukeScriptFromVfxHandoffManifest = (handoffManifest: string | HandoffWarningManifest) => {
  const manifest = parseManifest(handoffManifest);
  const project = manifest.project || {};
  const ocio = manifest.color?.openColorIO || {};
  const fps = Math.max(1, Math.round(toNumber(project.fps, 24)));
  const width = Math.max(16, Math.round(toNumber(project.width, 1920)));
  const height = Math.max(16, Math.round(toNumber(project.height, 1080)));
  const lastFrame = Math.max(1, Math.round(toNumber(project.timelineDurationFrames, 1)));
  const inputColorSpace = scriptString(ocio.inputColorSpace || 'Utility - Raw');
  const lines: string[] = [
    '# Generated by AI Video Production Editor',
    '# VFX handoff script for Nuke. Review paths, frame ranges, and colorspace before final comp.',
    'Root {',
    ` fps ${fps}`,
    ' first_frame 0',
    ` last_frame ${lastFrame}`,
    ` format "${width} ${height} 0 0 ${width} ${height} 1 AI_Video_Handoff"`,
    ' colorManagement OCIO',
  ];

  if (ocio.configPath) {
    lines.push(` OCIO_config "${escapeNuke(ocio.configPath)}"`);
  } else if (ocio.recommendedConfig) {
    lines.push(` OCIO_config "${escapeNuke(ocio.recommendedConfig)}"`);
  }
  lines.push('}');

  getReadyShots(manifest).forEach((shot, index) => {
    const nodeName = `Read_${sanitizeNodeName(shot.clipId || shot.clipName || index + 1)}`;
    const first = Math.max(0, Math.round(toNumber(shot.source?.handleInFrame, 0)));
    const last = Math.max(first, Math.round(toNumber(shot.source?.handleOutFrame, first + 1)));
    const x = (index % 4) * 220;
    const y = Math.floor(index / 4) * 180;
    lines.push(
      'Read {',
      ` file "${escapeNuke(shot.sourceUrl)}"`,
      ` first ${first}`,
      ` last ${last}`,
      ` origfirst ${first}`,
      ` origlast ${last}`,
      ` colorspace "${escapeNuke(inputColorSpace)}"`,
      ` name ${nodeName}`,
      ` label "${escapeNuke(`${shot.clipId || nodeName}\n${shot.trackName || ''}\nframes ${first}-${last}`)}"`,
      ` xpos ${x}`,
      ` ypos ${y}`,
      '}',
    );
  });

  getWarnings(manifest).forEach((warning, index) => {
    lines.push(
      'StickyNote {',
      ` label "WARNING: ${escapeNuke(warning)}"`,
      ` name Handoff_Warning_${index + 1}`,
      ` xpos ${index * 260}`,
      ' ypos -180',
      '}',
    );
  });

  return `${lines.join('\n')}\n`;
};

export const buildNatronPythonScriptFromVfxHandoffManifest = (handoffManifest: string | HandoffWarningManifest) => {
  const manifest = parseManifest(handoffManifest);
  const project = manifest.project || {};
  const ocio = manifest.color?.openColorIO || {};
  const fps = Math.max(1, Math.round(toNumber(project.fps, 24)));
  const width = Math.max(16, Math.round(toNumber(project.width, 1920)));
  const height = Math.max(16, Math.round(toNumber(project.height, 1080)));
  const inputColorSpace = scriptString(ocio.inputColorSpace || 'Utility - Raw');
  const lines: string[] = [
    '# Generated by AI Video Production Editor',
    '# VFX handoff script for Natron. Review plugin IDs and relink paths in your installed Natron build.',
    'import NatronEngine',
    '',
    'app = NatronEngine.natron.getInstance(0)',
    '',
    'def set_param(param, value):',
    '    try:',
    '        param.setValue(value)',
    '    except AttributeError:',
    '        param.set(value)',
    '',
    'def set_project_param(name, value):',
    '    try:',
    '        set_param(app.getProjectParam(name), value)',
    '    except Exception:',
    '        pass',
    '',
    'def create_read_node(name, filename, first_frame, last_frame, colorspace):',
    "    node = app.createNode('fr.inria.openfx.ReadOIIO')",
    "    node.setScriptName(name)",
    "    for param_name, value in [('filename', filename), ('firstFrame', first_frame), ('lastFrame', last_frame), ('colorspace', colorspace)]:",
    '        try:',
    '            set_param(node.getParam(param_name), value)',
    '        except Exception:',
    '            pass',
    '    return node',
    '',
    `set_project_param('fps', ${fps})`,
    `set_project_param('outputFormat', '${width}x${height}')`,
  ];

  if (ocio.configPath) {
    lines.push(`set_project_param('OCIOConfigFile', '${escapePython(ocio.configPath)}')`);
  } else if (ocio.recommendedConfig) {
    lines.push(`set_project_param('OCIOConfigFile', '${escapePython(ocio.recommendedConfig)}')`);
  }
  if (ocio.display) lines.push(`set_project_param('OCIODisplay', '${escapePython(ocio.display)}')`);
  if (ocio.view) lines.push(`set_project_param('OCIOView', '${escapePython(ocio.view)}')`);
  lines.push('');

  getReadyShots(manifest).forEach((shot, index) => {
    const variableName = `read_${sanitizeNodeName(shot.clipId || shot.clipName || index + 1).toLowerCase()}`;
    const nodeName = `Read_${sanitizeNodeName(shot.clipId || shot.clipName || index + 1)}`;
    const first = Math.max(0, Math.round(toNumber(shot.source?.handleInFrame, 0)));
    const last = Math.max(first, Math.round(toNumber(shot.source?.handleOutFrame, first + 1)));
    lines.push(`${variableName} = create_read_node('${nodeName}', '${escapePython(shot.sourceUrl)}', ${first}, ${last}, '${escapePython(inputColorSpace)}')`);
  });

  getWarnings(manifest).forEach((warning) => {
    lines.push(`# WARNING: ${warning}`);
  });

  return `${lines.join('\n')}\n`;
};

export const buildVfxApplicationScripts = (handoffManifest: string | HandoffWarningManifest): {
  nuke: VfxApplicationScript;
  natron: VfxApplicationScript;
} => ({
  nuke: {
    extension: 'nk',
    contents: buildNukeScriptFromVfxHandoffManifest(handoffManifest),
  },
  natron: {
    extension: 'py',
    contents: buildNatronPythonScriptFromVfxHandoffManifest(handoffManifest),
  },
});
