import test from 'node:test';
import assert from 'node:assert/strict';

const buildSampleHandoffManifest = async () => {
  const { buildVfxHandoffManifest } = await import('./vfxHandoffManifest.ts');

  return JSON.parse(buildVfxHandoffManifest({
    projectName: 'Shot Handoff',
    filename: 'shot_handoff_v001.mov',
    fps: 24,
    width: 2048,
    height: 858,
    colorProfile: 'rec2020-pq',
    bitDepth: 12,
    videoCodec: 'prores',
    container: 'mov',
    ocioConfigId: 'custom',
    ocioConfigPath: '/show/config/aces/shot.ocio',
    handleFrames: 12,
    mediaItems: [
      {
        id: 'plate',
        name: 'Plate.mov',
        type: 'video',
        url: 'blob:http://local/preview',
        sourceUrl: 'file:///show/plates/Plate.mov',
        source: 'upload',
        duration: 10,
      },
      {
        id: 'preview',
        name: 'PreviewOnly.mov',
        type: 'video',
        url: 'blob:http://local/preview-only',
        source: 'generated',
        duration: 2,
      },
    ],
    timelineTracks: [
      { id: 'v1', name: 'VFX Pull V1', type: 'video', isLocked: false, isMuted: false },
      { id: 'v2', name: 'VFX Pull V2', type: 'video', isLocked: false, isMuted: false },
    ],
    timelineClips: [
      {
        id: 'shot-010',
        mediaId: 'plate',
        trackId: 'v1',
        start: 0.5,
        end: 2.5,
        duration: 2,
        sourceIn: 1,
        sourceOut: 3,
        speed: 1,
        effect: null,
      },
      {
        id: 'preview-clip',
        mediaId: 'preview',
        trackId: 'v2',
        start: 3,
        end: 5,
        duration: 2,
        speed: 1,
        effect: null,
      },
    ],
  }));
};

test('buildNukeScriptFromVfxHandoffManifest creates a relinkable .nk with OCIO and Read nodes', async () => {
  const { buildNukeScriptFromVfxHandoffManifest } = await import('./vfxScriptExport.ts');
  const manifest = await buildSampleHandoffManifest();

  const script = buildNukeScriptFromVfxHandoffManifest(manifest);

  assert.match(script, /^# Generated by AI Video Production Editor/);
  assert.match(script, /Root \{\n fps 24\n first_frame 0\n last_frame 120\n format "2048 858 0 0 2048 858 1 AI_Video_Handoff"/);
  assert.match(script, /OCIO_config "\/show\/config\/aces\/shot\.ocio"/);
  assert.match(script, /Read \{\n file "file:\/\/\/show\/plates\/Plate\.mov"\n first 12\n last 84\n origfirst 12\n origlast 84\n colorspace "Utility - Linear - Rec\.2020"/);
  assert.match(script, /name Read_shot_010/);
  assert.match(script, /label "shot-010\\nVFX Pull V1\\nframes 12-84"/);
  assert.match(script, /StickyNote \{\n label "WARNING: Media \\"PreviewOnly\.mov\\" is preview-only/);
  assert.doesNotMatch(script, /blob:http/);
});

test('buildNatronPythonScriptFromVfxHandoffManifest creates a Natron import script with project settings', async () => {
  const { buildNatronPythonScriptFromVfxHandoffManifest } = await import('./vfxScriptExport.ts');
  const manifest = await buildSampleHandoffManifest();

  const script = buildNatronPythonScriptFromVfxHandoffManifest(manifest);

  assert.match(script, /^# Generated by AI Video Production Editor/);
  assert.match(script, /import NatronEngine/);
  assert.match(script, /set_project_param\('fps', 24\)/);
  assert.match(script, /set_project_param\('OCIOConfigFile', '\/show\/config\/aces\/shot\.ocio'\)/);
  assert.match(script, /set_project_param\('outputFormat', '2048x858'\)/);
  assert.match(script, /read_shot_010 = create_read_node\('Read_shot_010', 'file:\/\/\/show\/plates\/Plate\.mov', 12, 84, 'Utility - Linear - Rec\.2020'\)/);
  assert.match(script, /# WARNING: Media "PreviewOnly\.mov" is preview-only/);
  assert.doesNotMatch(script, /blob:http/);
});

test('buildVfxApplicationScripts returns both Nuke and Natron outputs', async () => {
  const { buildVfxApplicationScripts } = await import('./vfxScriptExport.ts');
  const manifest = await buildSampleHandoffManifest();

  const scripts = buildVfxApplicationScripts(manifest);

  assert.equal(scripts.nuke.extension, 'nk');
  assert.equal(scripts.natron.extension, 'py');
  assert.match(scripts.nuke.contents, /Read_shot_010/);
  assert.match(scripts.natron.contents, /read_shot_010/);
});
